### ISSUE TITLE
error after install: cannot find module 'warning'

### ISSUE THREAD

**Issue by jaredpalmer** [heroku/skeleton-4r#2]
Got this after a clean install and running `npm run dev`

```bash
module.js:338
    throw err;
    ^

Error: Cannot find module 'warning'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jaredpalmer/workspace/github/jaredpalmer/h4r/node_modules/create-render-4r/node_modules/history/lib/parsePath.js:7:16)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jaredpalmer/workspace/github/jaredpalmer/h4r/node_modules/babel-core/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.6
npm ERR! code ELIFECYCLE
npm ERR! skeleton-4r@1.0.0 dev: `NODE_PATH=$NODE_PATH:./app node ./app/dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the skeleton-4r@1.0.0 dev script 'NODE_PATH=$NODE_PATH:./app node ./app/dev-server'.
npm ERR! This is most likely a problem with the skeleton-4r package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_PATH=$NODE_PATH:./app node ./app/dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls skeleton-4r
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jaredpalmer/workspace/github/jaredpalmer/h4r/npm-debug.log
```

**Comment by mars** [comment]
Hi @jaredpalmer,

Thanks for sending this feedback. That `warning` module is a nested dependency, and I'm not sure why it would be missing. npm weirdness!

From the root of the repo, try resetting the packages by running:

```bash
rm -rf node_modules/ && npm cache clear
npm install
```

FYI, I just tried an `npm install` && `npm run dev` from master using Node 5.10, and it worked:

```bash
npm run dev

> skeleton-4r@1.0.0 dev /Users/mars.hall/Desktop/skeleton-4r-master
> NODE_PATH=$NODE_PATH:./app node ./app/dev-server

{ [Error: ENOENT: no such file or directory, open '.env'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
Dev Server listening on 3000
webpack built 24131dfcfa4df8e3a0cf in 2309ms
```

**Comment by jaredpalmer** [comment]
Will try later tonight and report results.

**Comment by estevanmontoya** [comment]
Thanks. I am working on a MeteorJS project. Reinstalling the modules and clearing the cache worked.
